package protocol

import "github.com/pingcap/ql"

var DefaultVariables = map[string]ql.SysVar{
	"character_set_database":                ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "latin1"},
	"gtid_mode":                             ql.SysVar{ql.ScopeGlobal, "", "OFF"},
	"range_alloc_block_size":                ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "4096"},
	"check_proxy_users":                     ql.SysVar{ql.ScopeGlobal, "", ""},
	"insert_id":                             ql.SysVar{ql.ScopeSession, "", ""},
	"innodb_rollback_segments":              ql.SysVar{ql.ScopeGlobal, "", "128"},
	"max_delayed_threads":                   ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "20"},
	"tmpdir":                                ql.SysVar{ql.ScopeNone, "", "/var/tmp/"},
	"ndb_log_empty_epochs":                  ql.SysVar{ql.ScopeGlobal, "", ""},
	"innodb_autoinc_lock_mode":              ql.SysVar{ql.ScopeNone, "", "1"},
	"key_cache_division_limit":              ql.SysVar{ql.ScopeGlobal, "", "100"},
	"max_binlog_size":                       ql.SysVar{ql.ScopeGlobal, "", "1073741824"},
	"query_alloc_block_size":                ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "8192"},
	"server_uuid":                           ql.SysVar{ql.ScopeNone, "", "d530594e-1c86-11e5-878b-6b36ce6799ca"},
	"binlog_error_action":                   ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "IGNORE_ERROR"},
	"innodb_disable_sort_file_cache":        ql.SysVar{ql.ScopeGlobal, "", "OFF"},
	"log_bin_trust_function_creators":       ql.SysVar{ql.ScopeGlobal, "", "OFF"},
	"binlog_format":                         ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "STATEMENT"},
	"innodb_sync_spin_loops":                ql.SysVar{ql.ScopeGlobal, "", "30"},
	"long_query_time":                       ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "10.000000"},
	"optimizer_trace":                       ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "enabled=off,one_line=off"},
	"transaction_allow_batching":            ql.SysVar{ql.ScopeSession, "", ""},
	"datadir":                               ql.SysVar{ql.ScopeNone, "", "/usr/local/mysql/data/"},
	"have_query_cache":                      ql.SysVar{ql.ScopeNone, "", "YES"},
	"have_symlink":                          ql.SysVar{ql.ScopeNone, "", "YES"},
	"innodb_api_enable_binlog":              ql.SysVar{ql.ScopeNone, "", "OFF"},
	"performance_schema_max_thread_classes": ql.SysVar{ql.ScopeNone, "", "50"},
	"query_cache_wlock_invalidate":          ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "OFF"},
	"timed_mutexes":                         ql.SysVar{ql.ScopeGlobal, "", "OFF"},
	"character_set_client":                  ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "latin1"},
	"default_tmp_storage_engine":            ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "InnoDB"},
	"innodb_checksum_algorithm":             ql.SysVar{ql.ScopeGlobal, "", "innodb"},
	"max_binlog_cache_size":                 ql.SysVar{ql.ScopeGlobal, "", "18446744073709547520"},
	"max_write_lock_count":                  ql.SysVar{ql.ScopeGlobal, "", "18446744073709551615"},
	"pseudo_thread_id":                      ql.SysVar{ql.ScopeSession, "", ""},
	"innodb_stats_persistent_sample_pages":  ql.SysVar{ql.ScopeGlobal, "", "20"},
	"innodb_spin_wait_delay":                ql.SysVar{ql.ScopeGlobal, "", "6"},
	"sql_buffer_result":                     ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "OFF"},
	"version_compile_os":                    ql.SysVar{ql.ScopeNone, "", "osx10.8"},
	"session_track_state_change":            ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", ""},
	"query_cache_type":                      ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "OFF"},
	"slave_load_tmpdir":                     ql.SysVar{ql.ScopeNone, "", "/var/tmp/"},
	"sql_select_limit":                      ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "18446744073709551615"},
	"log_syslog":                            ql.SysVar{ql.ScopeGlobal, "", ""},
	"max_allowed_packet":                    ql.SysVar{ql.ScopeGlobal, "", "4194304"},
	"performance_schema":                    ql.SysVar{ql.ScopeNone, "", "ON"},
	"pid_file":                              ql.SysVar{ql.ScopeNone, "", "/usr/local/mysql/data/localhost.pid"},
	"rpl_stop_slave_timeout":                ql.SysVar{ql.ScopeGlobal, "", "31536000"},
	"sql_notes":                             ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "ON"},
	"performance_schema_events_statements_history_long_size": ql.SysVar{ql.ScopeNone, "", "10000"},
	"thread_handling":                                        ql.SysVar{ql.ScopeNone, "", "one-thread-per-connection"},
	"innodb_monitor_reset":                                   ql.SysVar{ql.ScopeGlobal, "", ""},
	"binlog_checksum":                                        ql.SysVar{ql.ScopeGlobal, "", "CRC32"},
	"div_precision_increment":                                ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "4"},
	"max_prepared_stmt_count":                                ql.SysVar{ql.ScopeGlobal, "", "16382"},
	"open_files_limit":                                       ql.SysVar{ql.ScopeNone, "", "5000"},
	"optimizer_search_depth":                                 ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "62"},
	"ndb_show_foreign_key_mock_tables":                       ql.SysVar{ql.ScopeGlobal, "", ""},
	"validate_password_length":                               ql.SysVar{ql.ScopeGlobal, "", ""},
	"have_compress":                                          ql.SysVar{ql.ScopeNone, "", "YES"},
	"innodb_cmp_per_index_enabled":                           ql.SysVar{ql.ScopeGlobal, "", "OFF"},
	"sql_warnings":                                           ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "OFF"},
	"rand_seed2":                                             ql.SysVar{ql.ScopeSession, "", ""},
	"innodb_rollback_on_timeout":                             ql.SysVar{ql.ScopeNone, "", "OFF"},
	"log_backward_compatible_user_definitions":               ql.SysVar{ql.ScopeGlobal, "", ""},
	"license":                                 ql.SysVar{ql.ScopeNone, "", "GPL"},
	"report_port":                             ql.SysVar{ql.ScopeNone, "", "3306"},
	"log_error_verbosity":                     ql.SysVar{ql.ScopeGlobal, "", ""},
	"log_syslog_include_pid":                  ql.SysVar{ql.ScopeGlobal, "", ""},
	"ndb_force_send":                          ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", ""},
	"thread_concurrency":                      ql.SysVar{ql.ScopeNone, "", "10"},
	"character_set_results":                   ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "latin1"},
	"core_file":                               ql.SysVar{ql.ScopeNone, "", "OFF"},
	"innodb_flush_neighbors":                  ql.SysVar{ql.ScopeGlobal, "", "1"},
	"innodb_force_recovery":                   ql.SysVar{ql.ScopeNone, "", "0"},
	"innodb_purge_threads":                    ql.SysVar{ql.ScopeNone, "", "1"},
	"flush_time":                              ql.SysVar{ql.ScopeGlobal, "", "0"},
	"innodb_use_sys_malloc":                   ql.SysVar{ql.ScopeNone, "", "ON"},
	"max_seeks_for_key":                       ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "18446744073709551615"},
	"identity":                                ql.SysVar{ql.ScopeSession, "", ""},
	"auto_increment_offset":                   ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "1"},
	"skip_networking":                         ql.SysVar{ql.ScopeNone, "", "OFF"},
	"innodb_force_load_corrupted":             ql.SysVar{ql.ScopeNone, "", "OFF"},
	"lc_time_names":                           ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "en_US"},
	"optimizer_trace_features":                ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "greedy_search=on,range_optimizer=on,dynamic_range=on,repeated_subselect=on"},
	"slave_compressed_protocol":               ql.SysVar{ql.ScopeGlobal, "", "OFF"},
	"big_tables":                              ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "OFF"},
	"innodb_flush_log_at_trx_commit":          ql.SysVar{ql.ScopeGlobal, "", "1"},
	"innodb_log_files_in_group":               ql.SysVar{ql.ScopeNone, "", "2"},
	"max_relay_log_size":                      ql.SysVar{ql.ScopeGlobal, "", "0"},
	"performance_schema_max_thread_instances": ql.SysVar{ql.ScopeNone, "", "402"},
	"lc_messages":                             ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "en_US"},
	"lower_case_file_system":                  ql.SysVar{ql.ScopeNone, "", "ON"},
	"max_binlog_stmt_cache_size":              ql.SysVar{ql.ScopeGlobal, "", "18446744073709547520"},
	"flush": ql.SysVar{ql.ScopeGlobal, "", "OFF"},
	"innodb_buffer_pool_dump_now":                  ql.SysVar{ql.ScopeGlobal, "", "OFF"},
	"innodb_file_per_table":                        ql.SysVar{ql.ScopeGlobal, "", "ON"},
	"innodb_max_purge_lag":                         ql.SysVar{ql.ScopeGlobal, "", "0"},
	"innodb_undo_logs":                             ql.SysVar{ql.ScopeGlobal, "", "128"},
	"last_insert_id":                               ql.SysVar{ql.ScopeSession, "", ""},
	"ndbinfo_max_rows":                             ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", ""},
	"performance_schema_max_socket_instances":      ql.SysVar{ql.ScopeNone, "", "322"},
	"relay_log_purge":                              ql.SysVar{ql.ScopeGlobal, "", "ON"},
	"slave_parallel_workers":                       ql.SysVar{ql.ScopeGlobal, "", "0"},
	"stored_program_cache":                         ql.SysVar{ql.ScopeGlobal, "", "256"},
	"executed_gtids_compression_period":            ql.SysVar{ql.ScopeGlobal, "", ""},
	"sync_master_info":                             ql.SysVar{ql.ScopeGlobal, "", "10000"},
	"rpl_semi_sync_master_trace_level":             ql.SysVar{ql.ScopeGlobal, "", ""},
	"collation_connection":                         ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "latin1_swedish_ci"},
	"innodb_use_native_aio":                        ql.SysVar{ql.ScopeNone, "", "OFF"},
	"performance_schema_setup_objects_size":        ql.SysVar{ql.ScopeNone, "", "100"},
	"show_old_temporals":                           ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "OFF"},
	"storage_engine":                               ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "InnoDB"},
	"show_compatibility_56":                        ql.SysVar{ql.ScopeGlobal, "", ""},
	"event_scheduler":                              ql.SysVar{ql.ScopeGlobal, "", "OFF"},
	"innodb_flush_log_at_timeout":                  ql.SysVar{ql.ScopeGlobal, "", "1"},
	"log_bin_use_v1_row_events":                    ql.SysVar{ql.ScopeNone, "", "OFF"},
	"performance_schema_max_table_handles":         ql.SysVar{ql.ScopeNone, "", "4000"},
	"time_format":                                  ql.SysVar{ql.ScopeNone, "", "%H:%i:%s"},
	"validate_password_policy":                     ql.SysVar{ql.ScopeGlobal, "", ""},
	"concurrent_insert":                            ql.SysVar{ql.ScopeGlobal, "", "AUTO"},
	"performance_schema_events_waits_history_size": ql.SysVar{ql.ScopeNone, "", "10"},
	"sql_log_off":                                  ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "OFF"},
	"innodb_undo_log_truncate":                     ql.SysVar{ql.ScopeGlobal, "", ""},
	"ndb_deferred_constraints":                     ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", ""},
	"rpl_semi_sync_master_wait_no_slave":           ql.SysVar{ql.ScopeGlobal, "", ""},
	"innodb_compression_pad_pct_max":               ql.SysVar{ql.ScopeGlobal, "", "50"},
	"innodb_status_output_locks":                   ql.SysVar{ql.ScopeGlobal, "", "OFF"},
	"lc_messages_dir":                              ql.SysVar{ql.ScopeNone, "", "/usr/local/mysql-5.6.25-osx10.8-x86_64/share/"},
	"log_error":                                    ql.SysVar{ql.ScopeNone, "", "/usr/local/mysql/data/localhost.err"},
	"relay_log_recovery":                           ql.SysVar{ql.ScopeNone, "", "OFF"},
	"pseudo_slave_mode":                            ql.SysVar{ql.ScopeSession, "", ""},
	"log_throttle_queries_not_using_indexes":       ql.SysVar{ql.ScopeGlobal, "", "0"},
	"max_join_size":                                ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "18446744073709551615"},
	"max_length_for_sort_data":                     ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "1024"},
	"query_cache_limit":                            ql.SysVar{ql.ScopeGlobal, "", "1048576"},
	"innodb_optimize_point_storage":                ql.SysVar{ql.ScopeSession, "", ""},
	"bulk_insert_buffer_size":                      ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "8388608"},
	"innodb_log_file_size":                         ql.SysVar{ql.ScopeNone, "", "50331648"},
	"innodb_lru_scan_depth":                        ql.SysVar{ql.ScopeGlobal, "", "1024"},
	"ndb_log_binlog_index":                         ql.SysVar{ql.ScopeGlobal, "", ""},
	"innodb_ft_total_cache_size":                   ql.SysVar{ql.ScopeNone, "", "640000000"},
	"socket":                                       ql.SysVar{ql.ScopeNone, "", "/tmp/mysql.sock"},
	"max_points_in_geometry":                       ql.SysVar{ql.ScopeGlobal, "", ""},
	"ndb_distribution":                             ql.SysVar{ql.ScopeGlobal, "", ""},
	"rbr_exec_mode":                                ql.SysVar{ql.ScopeSession, "", ""},
	"keep_files_on_create":                         ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "OFF"},
	"performance_schema_max_cond_instances":        ql.SysVar{ql.ScopeNone, "", "3504"},
	"sql_mode":                                     ql.SysVar{ql.ScopeNone, "", "STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"},
	"innodb_ft_cache_size":                         ql.SysVar{ql.ScopeNone, "", "8000000"},
	"performance_schema_max_statement_classes":     ql.SysVar{ql.ScopeNone, "", "168"},
	"protocol_version":                             ql.SysVar{ql.ScopeNone, "", "10"},
	"query_prealloc_size":                          ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "8192"},
	"locked_in_memory":                             ql.SysVar{ql.ScopeNone, "", "OFF"},
	"performance_schema_max_mutex_instances":       ql.SysVar{ql.ScopeNone, "", "15906"},
	"group_concat_max_len":                         ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "1024"},
	"innodb_write_io_threads":                      ql.SysVar{ql.ScopeNone, "", "4"},
	"transaction_alloc_block_size":                 ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "8192"},
	"ndb_index_stat_option":                        ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", ""},
	"log_syslog_tag":                               ql.SysVar{ql.ScopeGlobal, "", ""},
	"innodb_stats_sample_pages":                    ql.SysVar{ql.ScopeGlobal, "", "8"},
	"myisam_data_pointer_size":                     ql.SysVar{ql.ScopeGlobal, "", "6"},
	"myisam_mmap_size":                             ql.SysVar{ql.ScopeNone, "", "18446744073709551615"},
	"performance_schema_max_mutex_classes":         ql.SysVar{ql.ScopeNone, "", "200"},
	"server_id":                                    ql.SysVar{ql.ScopeGlobal, "", "0"},
	"ft_boolean_syntax":                            ql.SysVar{ql.ScopeGlobal, "", "+ -><()~*:\"\"&|"},
	"innodb_buffer_pool_load_now":                  ql.SysVar{ql.ScopeGlobal, "", "OFF"},
	"innodb_buffer_pool_size":                      ql.SysVar{ql.ScopeGlobal, "", "134217728"},
	"innodb_commit_concurrency":                    ql.SysVar{ql.ScopeGlobal, "", "0"},
	"slave_rows_search_algorithms":                 ql.SysVar{ql.ScopeGlobal, "", "TABLE_SCAN,INDEX_SCAN"},
	"eq_range_index_dive_limit":                    ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "10"},
	"slave_exec_mode":                              ql.SysVar{ql.ScopeGlobal, "", "STRICT"},
	"innodb_fast_shutdown":                         ql.SysVar{ql.ScopeGlobal, "", "1"},
	"innodb_thread_concurrency":                    ql.SysVar{ql.ScopeGlobal, "", "0"},
	"max_sort_length":                              ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "1024"},
	"myisam_use_mmap":                              ql.SysVar{ql.ScopeGlobal, "", "OFF"},
	"innodb_ft_user_stopword_table":                ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", ""},
	"innodb_read_io_threads":                       ql.SysVar{ql.ScopeNone, "", "4"},
	"performance_schema_max_rwlock_instances":      ql.SysVar{ql.ScopeNone, "", "9102"},
	"character_set_filesystem":                     ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "binary"},
	"myisam_recover_options":                       ql.SysVar{ql.ScopeNone, "", "OFF"},
	"new": ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "OFF"},
	"innodb_log_write_ahead_size":                   ql.SysVar{ql.ScopeGlobal, "", ""},
	"innodb_undo_tablespaces":                       ql.SysVar{ql.ScopeNone, "", "0"},
	"performance_schema_hosts_size":                 ql.SysVar{ql.ScopeNone, "", "100"},
	"ft_min_word_len":                               ql.SysVar{ql.ScopeNone, "", "4"},
	"skip_external_locking":                         ql.SysVar{ql.ScopeNone, "", "ON"},
	"wait_timeout":                                  ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "28800"},
	"innodb_monitor_disable":                        ql.SysVar{ql.ScopeGlobal, "", ""},
	"innodb_adaptive_max_sleep_delay":               ql.SysVar{ql.ScopeGlobal, "", "150000"},
	"table_definition_cache":                        ql.SysVar{ql.ScopeGlobal, "", "1400"},
	"slave_net_timeout":                             ql.SysVar{ql.ScopeGlobal, "", "3600"},
	"sync_binlog":                                   ql.SysVar{ql.ScopeGlobal, "", "0"},
	"tx_read_only":                                  ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "OFF"},
	"innodb_buffer_pool_filename":                   ql.SysVar{ql.ScopeGlobal, "", "ib_buffer_pool"},
	"log_warnings":                                  ql.SysVar{ql.ScopeGlobal, "", "1"},
	"ndb_join_pushdown":                             ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", ""},
	"table_open_cache":                              ql.SysVar{ql.ScopeGlobal, "", "2000"},
	"have_geometry":                                 ql.SysVar{ql.ScopeNone, "", "YES"},
	"innodb_file_format":                            ql.SysVar{ql.ScopeGlobal, "", "Antelope"},
	"innodb_read_ahead_threshold":                   ql.SysVar{ql.ScopeGlobal, "", "56"},
	"local_infile":                                  ql.SysVar{ql.ScopeGlobal, "", "ON"},
	"skip_name_resolve":                             ql.SysVar{ql.ScopeNone, "", "OFF"},
	"collation_database":                            ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "latin1_swedish_ci"},
	"have_profiling":                                ql.SysVar{ql.ScopeNone, "", "YES"},
	"slave_allow_batching":                          ql.SysVar{ql.ScopeGlobal, "", "OFF"},
	"slave_skip_errors":                             ql.SysVar{ql.ScopeNone, "", "OFF"},
	"table_open_cache_instances":                    ql.SysVar{ql.ScopeNone, "", "1"},
	"internal_tmp_disk_storage_engine":              ql.SysVar{ql.ScopeGlobal, "", ""},
	"offline_mode":                                  ql.SysVar{ql.ScopeGlobal, "", ""},
	"basedir":                                       ql.SysVar{ql.ScopeNone, "", "/usr/local/mysql"},
	"init_connect":                                  ql.SysVar{ql.ScopeGlobal, "", ""},
	"performance_schema_max_rwlock_classes":         ql.SysVar{ql.ScopeNone, "", "40"},
	"character_set_system":                          ql.SysVar{ql.ScopeNone, "", "utf8"},
	"innodb_old_blocks_time":                        ql.SysVar{ql.ScopeGlobal, "", "1000"},
	"performance_schema_events_stages_history_size": ql.SysVar{ql.ScopeNone, "", "10"},
	"optimizer_trace_max_mem_size":                  ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "16384"},
	"foreign_key_checks":                            ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "ON"},
	"net_retry_count":                               ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "10"},
	"ndbinfo_show_hidden":                           ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", ""},
	"binlog_row_image":                              ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "FULL"},
	"innodb_api_enable_mdl":                         ql.SysVar{ql.ScopeNone, "", "OFF"},
	"max_insert_delayed_threads":                    ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "20"},
	"port": ql.SysVar{ql.ScopeNone, "", "3306"},
	"simplified_binlog_gtid_recovery":                    ql.SysVar{ql.ScopeNone, "", "OFF"},
	"innodb_adaptive_hash_index":                         ql.SysVar{ql.ScopeGlobal, "", "ON"},
	"innodb_api_disable_rowlock":                         ql.SysVar{ql.ScopeNone, "", "OFF"},
	"innodb_flushing_avg_loops":                          ql.SysVar{ql.ScopeGlobal, "", "30"},
	"key_cache_block_size":                               ql.SysVar{ql.ScopeGlobal, "", "1024"},
	"innodb_purge_rseg_truncate_frequency":               ql.SysVar{ql.ScopeGlobal, "", ""},
	"character_set_server":                               ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "latin1"},
	"innodb_api_trx_level":                               ql.SysVar{ql.ScopeGlobal, "", "0"},
	"net_read_timeout":                                   ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "30"},
	"init_slave":                                         ql.SysVar{ql.ScopeGlobal, "", ""},
	"old_passwords":                                      ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "0"},
	"skip_show_database":                                 ql.SysVar{ql.ScopeNone, "", "OFF"},
	"binlog_stmt_cache_size":                             ql.SysVar{ql.ScopeGlobal, "", "32768"},
	"log_slow_slave_statements":                          ql.SysVar{ql.ScopeGlobal, "", "OFF"},
	"net_buffer_length":                                  ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "16384"},
	"read_rnd_buffer_size":                               ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "262144"},
	"relay_log_info_file":                                ql.SysVar{ql.ScopeNone, "", "relay-log.info"},
	"large_pages":                                        ql.SysVar{ql.ScopeNone, "", "OFF"},
	"plugin_dir":                                         ql.SysVar{ql.ScopeNone, "", "/usr/local/mysql/lib/plugin/"},
	"slow_launch_time":                                   ql.SysVar{ql.ScopeGlobal, "", "2"},
	"performance_schema_digests_size":                    ql.SysVar{ql.ScopeNone, "", "10000"},
	"sync_relay_log":                                     ql.SysVar{ql.ScopeGlobal, "", "10000"},
	"log_timestamps":                                     ql.SysVar{ql.ScopeGlobal, "", ""},
	"binlog_gtid_simple_recovery":                        ql.SysVar{ql.ScopeNone, "", "OFF"},
	"large_files_support":                                ql.SysVar{ql.ScopeNone, "", "ON"},
	"performance_schema_session_connect_attrs_size":      ql.SysVar{ql.ScopeNone, "", "512"},
	"version_comment":                                    ql.SysVar{ql.ScopeNone, "", "MySQL Community Server (GPL)"},
	"ndb_blob_write_batch_bytes":                         ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", ""},
	"innodb_adaptive_flushing":                           ql.SysVar{ql.ScopeGlobal, "", "ON"},
	"myisam_sort_buffer_size":                            ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "8388608"},
	"sql_slave_skip_counter":                             ql.SysVar{ql.ScopeGlobal, "", "0"},
	"session_track_system_variables":                     ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", ""},
	"innodb_ft_enable_stopword":                          ql.SysVar{ql.ScopeGlobal, "", "ON"},
	"innodb_page_size":                                   ql.SysVar{ql.ScopeNone, "", "16384"},
	"metadata_locks_hash_instances":                      ql.SysVar{ql.ScopeNone, "", "8"},
	"binlog_max_flush_queue_time":                        ql.SysVar{ql.ScopeGlobal, "", "0"},
	"have_openssl":                                       ql.SysVar{ql.ScopeNone, "", "DISABLED"},
	"innodb_compression_failure_threshold_pct":           ql.SysVar{ql.ScopeGlobal, "", "5"},
	"preload_buffer_size":                                ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "32768"},
	"rewriter_enabled":                                   ql.SysVar{ql.ScopeGlobal, "", ""},
	"performance_schema_max_file_handles":                ql.SysVar{ql.ScopeNone, "", "32768"},
	"validate_password_mixed_case_count":                 ql.SysVar{ql.ScopeGlobal, "", ""},
	"general_log_file":                                   ql.SysVar{ql.ScopeGlobal, "", "/usr/local/mysql/data/localhost.log"},
	"innodb_random_read_ahead":                           ql.SysVar{ql.ScopeGlobal, "", "OFF"},
	"profiling_history_size":                             ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "15"},
	"ndb_index_stat_enable":                              ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", ""},
	"enforce_gtid_consistency":                           ql.SysVar{ql.ScopeGlobal, "", "OFF"},
	"innodb_api_bk_commit_interval":                      ql.SysVar{ql.ScopeGlobal, "", "5"},
	"innodb_stats_persistent":                            ql.SysVar{ql.ScopeGlobal, "", "ON"},
	"validate_password_number_count":                     ql.SysVar{ql.ScopeGlobal, "", ""},
	"query_cache_min_res_unit":                           ql.SysVar{ql.ScopeGlobal, "", "4096"},
	"innodb_monitor_enable":                              ql.SysVar{ql.ScopeGlobal, "", ""},
	"connect_timeout":                                    ql.SysVar{ql.ScopeGlobal, "", "10"},
	"delayed_insert_limit":                               ql.SysVar{ql.ScopeGlobal, "", "100"},
	"innodb_ft_result_cache_limit":                       ql.SysVar{ql.ScopeGlobal, "", "2000000000"},
	"interactive_timeout":                                ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "28800"},
	"performance_schema_accounts_size":                   ql.SysVar{ql.ScopeNone, "", "100"},
	"rpl_semi_sync_slave_trace_level":                    ql.SysVar{ql.ScopeGlobal, "", ""},
	"auto_increment_increment":                           ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "1"},
	"date_format":                                        ql.SysVar{ql.ScopeNone, "", "%Y-%m-%d"},
	"innodb_checksums":                                   ql.SysVar{ql.ScopeNone, "", "ON"},
	"secure_auth":                                        ql.SysVar{ql.ScopeGlobal, "", "ON"},
	"thread_cache_size":                                  ql.SysVar{ql.ScopeGlobal, "", "9"},
	"max_sp_recursion_depth":                             ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "0"},
	"ignore_builtin_innodb":                              ql.SysVar{ql.ScopeNone, "", "OFF"},
	"log_slave_updates":                                  ql.SysVar{ql.ScopeNone, "", "OFF"},
	"innodb_fill_factor":                                 ql.SysVar{ql.ScopeGlobal, "", ""},
	"mysql_native_password_proxy_users":                  ql.SysVar{ql.ScopeGlobal, "", ""},
	"innodb_adaptive_flushing_lwm":                       ql.SysVar{ql.ScopeGlobal, "", "10"},
	"innodb_concurrency_tickets":                         ql.SysVar{ql.ScopeGlobal, "", "5000"},
	"innodb_ft_sort_pll_degree":                          ql.SysVar{ql.ScopeNone, "", "2"},
	"log_slow_admin_statements":                          ql.SysVar{ql.ScopeGlobal, "", "OFF"},
	"relay_log_space_limit":                              ql.SysVar{ql.ScopeNone, "", "0"},
	"rpl_semi_sync_master_timeout":                       ql.SysVar{ql.ScopeGlobal, "", ""},
	"validate_password_special_char_count":               ql.SysVar{ql.ScopeGlobal, "", ""},
	"ft_stopword_file":                                   ql.SysVar{ql.ScopeNone, "", "(built-in)"},
	"innodb_large_prefix":                                ql.SysVar{ql.ScopeGlobal, "", "OFF"},
	"slave_checkpoint_group":                             ql.SysVar{ql.ScopeGlobal, "", "512"},
	"slave_transaction_retries":                          ql.SysVar{ql.ScopeGlobal, "", "10"},
	"ndb_table_no_logging":                               ql.SysVar{ql.ScopeSession, "", ""},
	"slave_max_allowed_packet":                           ql.SysVar{ql.ScopeGlobal, "", "1073741824"},
	"rpl_semi_sync_master_enabled":                       ql.SysVar{ql.ScopeGlobal, "", ""},
	"innodb_monitor_reset_all":                           ql.SysVar{ql.ScopeGlobal, "", ""},
	"automatic_sp_privileges":                            ql.SysVar{ql.ScopeGlobal, "", "ON"},
	"character_set_connection":                           ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "latin1"},
	"have_ssl":                                           ql.SysVar{ql.ScopeNone, "", "DISABLED"},
	"multi_range_count":                                  ql.SysVar{ql.ScopeNone, "", "256"},
	"innodb_ft_server_stopword_table":                    ql.SysVar{ql.ScopeGlobal, "", ""},
	"profiling":                                          ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "OFF"},
	"max_statement_time":                                 ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", ""},
	"binlog_cache_size":                                  ql.SysVar{ql.ScopeGlobal, "", "32768"},
	"innodb_log_group_home_dir":                          ql.SysVar{ql.ScopeNone, "", "./"},
	"innodb_sort_buffer_size":                            ql.SysVar{ql.ScopeNone, "", "1048576"},
	"key_cache_age_threshold":                            ql.SysVar{ql.ScopeGlobal, "", "300"},
	"performance_schema_max_file_instances":              ql.SysVar{ql.ScopeNone, "", "7693"},
	"collation_server":                                   ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "latin1_swedish_ci"},
	"innodb_buffer_pool_instances":                       ql.SysVar{ql.ScopeNone, "", "8"},
	"innodb_stats_method":                                ql.SysVar{ql.ScopeGlobal, "", "nulls_equal"},
	"innodb_replication_delay":                           ql.SysVar{ql.ScopeGlobal, "", "0"},
	"innodb_status_output":                               ql.SysVar{ql.ScopeGlobal, "", "OFF"},
	"min_examined_row_limit":                             ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "0"},
	"sql_log_bin":                                        ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "ON"},
	"optimizer_switch":                                   ql.SysVar{ql.ScopeNone, "", "index_merge=on,index_merge_union=on,index_merge_sort_union=on,index_merge_intersection=on,engine_condition_pushdown=on,index_condition_pushdown=on,mrr=on,mrr_cost_based=on,block_nested_loop=on,batched_key_access=off,materialization=on,semijoin=on,loosescan=on,firstmatch=on,subquery_materialization_cost_based=on,use_index_extensions=on"},
	"server_id_bits":                                     ql.SysVar{ql.ScopeNone, "", "32"},
	"lower_case_table_names":                             ql.SysVar{ql.ScopeNone, "", "2"},
	"myisam_repair_threads":                              ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "1"},
	"old_alter_table":                                    ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "OFF"},
	"sha256_password_proxy_users":                        ql.SysVar{ql.ScopeGlobal, "", ""},
	"default_storage_engine":                             ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "InnoDB"},
	"host_cache_size":                                    ql.SysVar{ql.ScopeGlobal, "", "279"},
	"innodb_version":                                     ql.SysVar{ql.ScopeNone, "", "5.6.25"},
	"performance_schema_max_cond_classes":                ql.SysVar{ql.ScopeNone, "", "80"},
	"log_syslog_facility":                                ql.SysVar{ql.ScopeGlobal, "", ""},
	"have_dynamic_loading":                               ql.SysVar{ql.ScopeNone, "", "YES"},
	"myisam_max_sort_file_size":                          ql.SysVar{ql.ScopeGlobal, "", "9223372036853727232"},
	"sql_quote_show_create":                              ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "ON"},
	"slave_preserve_commit_order":                        ql.SysVar{ql.ScopeGlobal, "", ""},
	"join_buffer_size":                                   ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "262144"},
	"performance_schema_max_socket_classes":              ql.SysVar{ql.ScopeNone, "", "10"},
	"read_only":                                          ql.SysVar{ql.ScopeGlobal, "", "OFF"},
	"max_tmp_tables":                                     ql.SysVar{ql.ScopeNone, "", "32"},
	"rpl_semi_sync_slave_enabled":                        ql.SysVar{ql.ScopeGlobal, "", ""},
	"binlog_direct_non_transactional_updates":            ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "OFF"},
	"myisam_stats_method":                                ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "nulls_unequal"},
	"performance_schema_max_table_instances":             ql.SysVar{ql.ScopeNone, "", "12500"},
	"innodb_log_checksum_algorithm":                      ql.SysVar{ql.ScopeGlobal, "", ""},
	"end_markers_in_json":                                ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "OFF"},
	"innodb_data_file_path":                              ql.SysVar{ql.ScopeNone, "", "ibdata1:12M:autoextend"},
	"max_connections":                                    ql.SysVar{ql.ScopeGlobal, "", "151"},
	"performance_schema_events_stages_history_long_size": ql.SysVar{ql.ScopeNone, "", "10000"},
	"slave_pending_jobs_size_max":                        ql.SysVar{ql.ScopeGlobal, "", "16777216"},
	"block_encryption_mode":                              ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "aes-128-ecb"},
	"default_week_format":                                ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "0"},
	"log_output":                                         ql.SysVar{ql.ScopeNone, "", "FILE"},
	"avoid_temporal_upgrade":                             ql.SysVar{ql.ScopeGlobal, "", "OFF"},
	"innodb_change_buffer_max_size":                      ql.SysVar{ql.ScopeGlobal, "", "25"},
	"max_error_count":                                    ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "64"},
	"innodb_max_undo_log_size":                           ql.SysVar{ql.ScopeGlobal, "", ""},
	"innodb_file_format_max":                             ql.SysVar{ql.ScopeGlobal, "", "Antelope"},
	"innodb_undo_directory":                              ql.SysVar{ql.ScopeNone, "", "."},
	"net_write_timeout":                                  ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "60"},
	"rpl_semi_sync_master_wait_point":                    ql.SysVar{ql.ScopeGlobal, "", ""},
	"max_user_connections":                               ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "0"},
	"old": ql.SysVar{ql.ScopeNone, "", "OFF"},
	"performance_schema_events_statements_history_size": ql.SysVar{ql.ScopeNone, "", "10"},
	"unique_checks":                                     ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "ON"},
	"rewriter_verbose":                                  ql.SysVar{ql.ScopeGlobal, "", ""},
	"sql_safe_updates":                                  ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "OFF"},
	"explicit_defaults_for_timestamp":                   ql.SysVar{ql.ScopeNone, "", "OFF"},
	"general_log":                                       ql.SysVar{ql.ScopeGlobal, "", "OFF"},
	"innodb_mirrored_log_groups":                        ql.SysVar{ql.ScopeNone, "", "1"},
	"performance_schema_events_waits_history_long_size": ql.SysVar{ql.ScopeNone, "", "10000"},
	"performance_schema_users_size":                     ql.SysVar{ql.ScopeNone, "", "100"},
	"version_compile_machine":                           ql.SysVar{ql.ScopeNone, "", "x86_64"},
	"super_read_only":                                   ql.SysVar{ql.ScopeGlobal, "", ""},
	"sync_relay_log_info":                               ql.SysVar{ql.ScopeGlobal, "", "10000"},
	"time_zone":                                         ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "SYSTEM"},
	"rand_seed1":                                        ql.SysVar{ql.ScopeSession, "", ""},
	"ft_query_expansion_limit":                          ql.SysVar{ql.ScopeNone, "", "20"},
	"innodb_ft_min_token_size":                          ql.SysVar{ql.ScopeNone, "", "3"},
	"innodb_lock_wait_timeout":                          ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "50"},
	"innodb_optimize_fulltext_only":                     ql.SysVar{ql.ScopeGlobal, "", "OFF"},
	"innodb_support_xa":                                 ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "ON"},
	"delay_key_write":                                   ql.SysVar{ql.ScopeGlobal, "", "ON"},
	"max_connect_errors":                                ql.SysVar{ql.ScopeGlobal, "", "100"},
	"innodb_max_purge_lag_delay":                        ql.SysVar{ql.ScopeGlobal, "", "0"},
	"slow_query_log_file":                               ql.SysVar{ql.ScopeGlobal, "", "/usr/local/mysql/data/localhost-slow.log"},
	"innodb_buffer_pool_dump_pct":                       ql.SysVar{ql.ScopeGlobal, "", ""},
	"bind_address":                                      ql.SysVar{ql.ScopeNone, "", "*"},
	"innodb_doublewrite":                                ql.SysVar{ql.ScopeNone, "", "ON"},
	"innodb_max_dirty_pages_pct_lwm":                    ql.SysVar{ql.ScopeGlobal, "", "0"},
	"lock_wait_timeout":                                 ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "31536000"},
	"low_priority_updates":                              ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "OFF"},
	"debug":                                             ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", ""},
	"ndb_optimization_delay":                            ql.SysVar{ql.ScopeGlobal, "", ""},
	"innodb_buffer_pool_load_abort":                     ql.SysVar{ql.ScopeGlobal, "", "OFF"},
	"innodb_sync_array_size":                            ql.SysVar{ql.ScopeNone, "", "1"},
	"large_page_size":                                   ql.SysVar{ql.ScopeNone, "", "0"},
	"slave_sql_verify_checksum":                         ql.SysVar{ql.ScopeGlobal, "", "ON"},
	"tmp_table_size":                                    ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "16777216"},
	"disconnect_on_expired_password":                    ql.SysVar{ql.ScopeNone, "", "ON"},
	"hostname":                                          ql.SysVar{ql.ScopeNone, "", "localhost"},
	"innodb_stats_on_metadata":                          ql.SysVar{ql.ScopeGlobal, "", "OFF"},
	"system_time_zone":                                  ql.SysVar{ql.ScopeNone, "", "CST"},
	"innodb_compression_level":                          ql.SysVar{ql.ScopeGlobal, "", "6"},
	"default_password_lifetime":                         ql.SysVar{ql.ScopeGlobal, "", ""},
	"innodb_max_dirty_pages_pct":                        ql.SysVar{ql.ScopeGlobal, "", "75"},
	"performance_schema_max_file_classes":               ql.SysVar{ql.ScopeNone, "", "50"},
	"slave_checkpoint_period":                           ql.SysVar{ql.ScopeGlobal, "", "300"},
	"session_track_schema":                              ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", ""},
	"performance_schema_max_stage_classes":              ql.SysVar{ql.ScopeNone, "", "150"},
	"thread_stack":                                      ql.SysVar{ql.ScopeNone, "", "262144"},
	"validate_password_dictionary_file":                 ql.SysVar{ql.ScopeGlobal, "", ""},
	"performance_schema_setup_actors_size":              ql.SysVar{ql.ScopeNone, "", "100"},
	"slow_query_log":                                    ql.SysVar{ql.ScopeGlobal, "", "OFF"},
	"sync_frm":                                          ql.SysVar{ql.ScopeGlobal, "", "ON"},
	"autocommit":                                        ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "ON"},
	"have_rtree_keys":                                   ql.SysVar{ql.ScopeNone, "", "YES"},
	"innodb_change_buffering":                           ql.SysVar{ql.ScopeGlobal, "", "all"},
	"innodb_io_capacity":                                ql.SysVar{ql.ScopeGlobal, "", "200"},
	"key_buffer_size":                                   ql.SysVar{ql.ScopeGlobal, "", "8388608"},
	"transaction_write_set_extraction":                  ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", ""},
	"expire_logs_days":                                  ql.SysVar{ql.ScopeGlobal, "", "0"},
	"innodb_io_capacity_max":                            ql.SysVar{ql.ScopeGlobal, "", "2000"},
	"innodb_strict_mode":                                ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "OFF"},
	"sql_big_selects":                                   ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "ON"},
	"binlog_group_commit_sync_delay":                    ql.SysVar{ql.ScopeGlobal, "", ""},
	"innodb_buffer_pool_load_at_startup":                ql.SysVar{ql.ScopeNone, "", "OFF"},
	"optimizer_trace_limit":                             ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "1"},
	"updatable_views_with_limit":                        ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "YES"},
	"ndb_recv_thread_cpu_mask":                          ql.SysVar{ql.ScopeNone, "", ""},
	"debug_sync":                                        ql.SysVar{ql.ScopeSession, "", ""},
	"innodb_create_intrinsic":                           ql.SysVar{ql.ScopeSession, "", ""},
	"ndb_use_transactions":                              ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", ""},
	"delayed_queue_size":                                ql.SysVar{ql.ScopeGlobal, "", "1000"},
	"innodb_log_buffer_size":                            ql.SysVar{ql.ScopeNone, "", "8388608"},
	"innodb_log_compressed_pages":                       ql.SysVar{ql.ScopeGlobal, "", "ON"},
	"innodb_purge_batch_size":                           ql.SysVar{ql.ScopeGlobal, "", "300"},
	"metadata_locks_cache_size":                         ql.SysVar{ql.ScopeNone, "", "1024"},
	"rpl_semi_sync_master_wait_for_slave_count":         ql.SysVar{ql.ScopeGlobal, "", ""},
	"gtid_purged":                                       ql.SysVar{ql.ScopeGlobal, "", ""},
	"innodb_ft_num_word_optimize":                       ql.SysVar{ql.ScopeGlobal, "", "2000"},
	"innodb_locks_unsafe_for_binlog":                    ql.SysVar{ql.ScopeNone, "", "OFF"},
	"innodb_open_files":                                 ql.SysVar{ql.ScopeNone, "", "2000"},
	"innodb_thread_sleep_delay":                         ql.SysVar{ql.ScopeGlobal, "", "10000"},
	"log_bin":                                           ql.SysVar{ql.ScopeNone, "", "OFF"},
	"innodb_autoextend_increment":                       ql.SysVar{ql.ScopeGlobal, "", "64"},
	"innodb_read_only":                                  ql.SysVar{ql.ScopeNone, "", "OFF"},
	"transaction_prealloc_size":                         ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "4096"},
	"version":                                           ql.SysVar{ql.ScopeNone, "", "5.6.25"},
	"datetime_format":                                   ql.SysVar{ql.ScopeNone, "", "%Y-%m-%d %H:%i:%s"},
	"ft_max_word_len":                                   ql.SysVar{ql.ScopeNone, "", "84"},
	"innodb_additional_mem_pool_size":                   ql.SysVar{ql.ScopeNone, "", "8388608"},
	"gtid_executed_compression_period":                  ql.SysVar{ql.ScopeGlobal, "", ""},
	"innodb_flush_sync":                                 ql.SysVar{ql.ScopeGlobal, "", ""},
	"innodb_ft_max_token_size":                          ql.SysVar{ql.ScopeNone, "", "84"},
	"innodb_stats_auto_recalc":                          ql.SysVar{ql.ScopeGlobal, "", "ON"},
	"master_info_repository":                            ql.SysVar{ql.ScopeGlobal, "", "FILE"},
	"binlog_order_commits":                              ql.SysVar{ql.ScopeGlobal, "", "ON"},
	"binlogging_impossible_mode":                        ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "IGNORE_ERROR"},
	"binlog_group_commit_sync_no_delay_count":           ql.SysVar{ql.ScopeGlobal, "", ""},
	"ndb_eventbuffer_free_percent":                      ql.SysVar{ql.ScopeGlobal, "", ""},
	"slave_parallel_type":                               ql.SysVar{ql.ScopeGlobal, "", ""},
	"max_digest_length":                                 ql.SysVar{ql.ScopeNone, "", "1024"},
	"read_buffer_size":                                  ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "131072"},
	"session_track_gtids":                               ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", ""},
	"query_cache_size":                                  ql.SysVar{ql.ScopeGlobal, "", "1048576"},
	"back_log":                                          ql.SysVar{ql.ScopeNone, "", "80"},
	"innodb_online_alter_log_max_size":                  ql.SysVar{ql.ScopeGlobal, "", "134217728"},
	"innodb_ft_aux_table":                               ql.SysVar{ql.ScopeGlobal, "", ""},
	"completion_type":                                   ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "NO_CHAIN"},
	"innodb_print_all_deadlocks":                        ql.SysVar{ql.ScopeGlobal, "", "OFF"},
	"ndb_log_updated_only":                              ql.SysVar{ql.ScopeGlobal, "", ""},
	"have_crypt":                                        ql.SysVar{ql.ScopeNone, "", "YES"},
	"innodb_ft_enable_diag_print":                       ql.SysVar{ql.ScopeGlobal, "", "OFF"},
	"innodb_table_locks":                                ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "ON"},
	"log_queries_not_using_indexes":                     ql.SysVar{ql.ScopeGlobal, "", "OFF"},
	"max_heap_table_size":                               ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "16777216"},
	"innodb_old_blocks_pct":                             ql.SysVar{ql.ScopeGlobal, "", "37"},
	"optimizer_prune_level":                             ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "1"},
	"gtid_next":                                         ql.SysVar{ql.ScopeSession, "", ""},
	"sql_auto_is_null":                                  ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "OFF"},
	"delayed_insert_timeout":                            ql.SysVar{ql.ScopeGlobal, "", "300"},
	"innodb_file_format_check":                          ql.SysVar{ql.ScopeNone, "", "ON"},
	"master_verify_checksum":                            ql.SysVar{ql.ScopeGlobal, "", "OFF"},
	"timestamp":                                         ql.SysVar{ql.ScopeSession, "", ""},
	"character_sets_dir":                                ql.SysVar{ql.ScopeNone, "", "/usr/local/mysql-5.6.25-osx10.8-x86_64/share/charsets/"},
	"innodb_stats_transient_sample_pages":               ql.SysVar{ql.ScopeGlobal, "", "8"},
	"relay_log_info_repository":                         ql.SysVar{ql.ScopeGlobal, "", "FILE"},
	"sort_buffer_size":                                  ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "262144"},
	"ndb_eventbuffer_max_alloc":                         ql.SysVar{ql.ScopeGlobal, "", ""},
	"optimizer_trace_offset":                            ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "-1"},
	"tx_isolation":                                      ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "REPEATABLE-READ"},
	"binlog_rows_query_log_events":                      ql.SysVar{ql.ScopeGlobal | ql.ScopeSession, "", "OFF"},
	"innodb_buffer_pool_dump_at_shutdown":               ql.SysVar{ql.ScopeGlobal, "", "OFF"},
}
